### ISSUE TITLE
MviViewModel update

### ISSUE THREAD

**Issue by margarita-v** [ruslansharipov/mvi-flow#3]
It's possible to make MviViewModel as an abstract class and inherit it from ViewModel, so the base setup could be moved here as well. MviViewModel could be moved to mvi-flow-lifecycle

**Comment by ruslansharipov** [comment]
That's what I was afraid of doing. Making fields like middleware abstract in the base class would make them visible for all users of the descendant viewmodels. 
Let's hope that no one will use it in non expected way.
Otherwise we would need to create something very overcomplicated like Relation interface in mvp-binding. In order to prevent the access.
But I like the idea of making all setup in one place during the initializing. let's give it a try
